### ISSUE TITLE
Alliance Mgmt Tool

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#110]
How about a Tap n Hold on the Deposit and Withdraw buttons to open the alliance 'books'. Maybe similar to the annotate. Listing all member money rqsts. Since everyone enters a dep or draw, listing them should be easy. The alliance leader could also choose officers here as well. A pending votes button added next to dep n draw or maybe make it a two-fer to list votes and one to submit for vote.

**Comment by Hexan1** [comment]
The submit for vote could be broadened to include posting suggestions as well.

**Comment by Hexan1** [comment]
Maybe change Deposit to one of three categories: specific other player, dues etc. to general fund, or to one's personal bank acct. Loan repayment track would be useful. Being able to move cash outside to another alliance, would eliminate the need to create alts to 'visit' a foreign alliance. A workable seems doable, with cross-checks to prevent abuse.

**Comment by codeka** [comment]
Cash won't exist in v2 so this doesn't make sense any more.
