### ISSUE TITLE
Zero star player entries

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#113]
There are a number of players on the Empire list with zero colonies and stars, yet many of these same stars have been colonized by others, creating a data cross match. This needs clearing.

**Comment by coherentones** [comment]
I use some of these zero star empires to jump around the map from the empire screen.

**Comment by codeka** [comment]
I they ever log in again, they'll be assigned a new star but the system doesn't assign them a new star until that happens. I should probably go through and clear them out or something.

**Comment by codeka** [comment]
This is basically the same issue as #89.
