### ISSUE TITLE
Help the Newbie

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#114]
Change the Start up Kit. Gift them all with 20 million seed money and be done with it. Better yet give them all fifty-star starter empires...

**Comment by codeka** [comment]
Hmm, I understand the reason for this but I kind of like the way the alliances help new players with funds. I guess it might turn away some people who don't want to join alliances. I'll think about it :)

**Comment by Hexan1** [comment]
I get so darn irritated at all these newbs that don't wanna wait for gratification. Game is a slow build, of course, but game might benefit from a bigger starter kit cash pot. More ships at start might make things seem less precarious and minimal. They all seem to expect gobs of different ships n weapons....an emphasis on ships and fleet composition. Maybe think on mixed fleet flights, single flight send to a star for simplicity but retain same ship speeds as now. Not having to do multiple sends...send col ship, send fighters, send troopies, etc. Send all at once. Ask if they want to add to the flight group before doing the move. Maybe show a ship type arrival comparison for timing sake. Ask "Wanna boost any ships?" Allow up to 3 boosting bumps to your fleet per trip.

-------- Original message --------

**Comment by codeka** [comment]
I'm hoping v2 will have a faster start-game.
