### ISSUE TITLE
Tac View enhanced

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#117]
While the globes mark both colonies and fleets only, it would be helpful having the fleet-only stars overlay the map with small blue or yellow rings. This would be a very good way of overviewing one's empire. Or maybe it would be neater to ring the globes of fleet-only stars. However, large rings would overlap in line with the primary globes, which also overlap each other. That would probably be too confusing. Basically I was looking for a tidy method of separating uncompleted development from the whole.
I know I mentioned similar for the galactic display. Not sure which would make a better 'work progress', doing this markup on the standard Zoomer or leaving it to be a part of Tac. Tac is meant to be an overview mode of course.

**Comment by codeka** [comment]
OK I've actually gone ahead and done this using partially-transparent circles if there's only ships at a star:

![screenshot_2015-03-08-17-52-53](https://cloud.githubusercontent.com/assets/1569910/6544952/31501a7e-c5bc-11e4-8d95-7b3b7dffb202.png)
