### ISSUE TITLE
The Options header at game start overlaps the choosing of background

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#118]
The Options header at game start overlaps the choosing of background.

**Comment by Hexan1** [comment]
Double chat entries on user side.  They go away on exiting chat and reentering chat,

**Comment by Hexan1** [comment]
Locate button wks great. Lft/Rt alpha swipe of solar no longer works, was that planned? Some may want that alpha swipe back. Also, adding a jump function of Locate when the star search drop down is open...tap of Locate would jump you to current stars's place in the list(when no star is highlighted). This would give you 2 ways to alpha search, plus the new galactic view Locate.
Highlighting a star on the alpha list and tapping Locate would expand the Locate to allow jumps to SPECIFIC stars(on galactic view) as well. A major enhance of searches....

**Comment by Hexan1** [comment]
Adding a Locate button to the Fleets pane would allow zeroing in on specific fleets, both stationed, and moving, on the Galactic View.

**Comment by Hexan1** [comment]
Minor problem: the Locate panel is a smidge too wide and partly covers the buffers.

**Comment by coherentones** [comment]
Fleets in flight no longer display in star view.

**Comment by coherentones** [comment]
Alliance Requests tab causes WW to stop.

**Comment by codeka** [comment]
I split off the other issues into separate bugs, this one is now just about the options header.
