### ISSUE TITLE
Integer overflow in display of cash

### ISSUE THREAD

**Issue by codeka** [codeka/wwmmo#144]
Some players have over $2B, which overflows and displays as a large negative number instead. Might be better to also truncate a bit and display $3.4B or something instead of $3,450,302,429 which is kinda useless?

**Comment by Gloomyempire** [comment]
Having it only show $3,450.3 million might be a little more convenient as a meaningful purchase would cost around $100k+. I think the same should apply for alliance bank. Seems a little silly to be able to deposit less than $1000 when you can only build like 4 buildings with it and many of the times when a small amount is submitted it won't show the correct amount. Could you limit the deposit amount there too?

**Comment by codeka** [comment]
I'm going to mark this fixed for now, I think changing the display format is doable, but for now there's probably not much benefit.

One thing I'd like to do is adjust the speed at which it updates itself. If you deposit millions into your alliance count, it'll just count down too slowly...
