### ISSUE TITLE
Bug -destroyed system still spawn ship builds

### ISSUE THREAD

**Issue by cbryancu** [codeka/wwmmo#155]
If you destroy a system, remove all structures, if you do not colonize all planets, the previous owners ship queues continue to spawn. I believe the shipyard queue should be removed once a shipyard is destroyed.

**Comment by codeka** [comment]
Not yet, I have to update the server still.

**Comment by cbryancu** [comment]
7 min ago I got another ghost spawn. So dont think it's fixed, or this is
an alt account who hacked the game.
There is a player who has repeatedly attack me with alt accounts trying to
deplete my bank. or get me to appear to start something bigger. I have been
hit by the virus removal account which is a bot account ran by same player.
I believe many of his alliance are bot run or bot aided accounts which
seems unfair to goal of game, but I cant prove anything.

Since you gave info to allow maps, which seems great, except now player
dont need to scout to find where outposts are. It encourages the create a
new account to see if it spawns closer to a target. That must help bog down
server.

Anyway bug it still occurring with fleet spawning after system has been
cleared of that account.

**Comment by cbryancu** [comment]
FYI game not allowing logins again
