### ISSUE TITLE
Remove assumptions from shell scripts

### ISSUE THREAD

**Issue by bibby** [codeka/wwmmo#2]
As mentioned in the [blog post](http://www.war-worlds.com/forum/development/getting-started-read-this-to-get-started-building-the-code),

> The scripts in the scripts/ folder should help with building the various components, but they may need some tweaking.

The current shell scripts (`run-server.sh`, `run-client.sh`, etc) make assumptions about their position relative to the source directories, including the name of which the repository was cloned (`code/server`).

These scripts could have these assumptions removed or at least relaxed. If nothing else, they could assume a position that matches the repository layout, making them instantly usable.

**Comment by codeka** [comment]
v2 is moving away from shell scripts and being completely driven by gradle.
