### ISSUE TITLE
System Resources display +0/hr

### ISSUE THREAD

**Issue by IronSkillet** [codeka/wwmmo#76]
The issue Val brought up previously persists for both he and I.  This is all planets, at all times.  As soon as I do anything in a system resources revert to 0 and stay that way until a force close and restart.  I've cleared app cache as well as phone cache.  Have also uninstalled and reinstalled various versions.  The last version that worked for me was .830.
![screenshot_2014-11-27-09-48-22](https://cloud.githubusercontent.com/assets/9977830/5218513/d141576e-761b-11e4-8628-c34dd85651ae.png)
![screenshot_2014-11-27-09-48-35](https://cloud.githubusercontent.com/assets/9977830/5218515/d58d0a52-761b-11e4-9620-a05c6c431084.png)

**Comment by codeka** [comment]
OK, I'm pretty confident this is now fixed by commit e9582a69952a170fde5fab9bcbef4e0ce99f29a4, I'm planning a new update very soon now.
