### ISSUE TITLE
shield purchase 

### ISSUE THREAD

**Issue by reaversofwarworlds** [codeka/wwmmo#87]
Unable to generate or purchase shield as in app purchase

**Comment by reaversofwarworlds** [comment]
Still an issue with the shield not uploading after purchase,  the toggle of the tabs helped load image but failed to load after purchase, one player has attempted 4 times but had to request refund from Google each time because purchase failed.

**Comment by codeka** [comment]
The above commit fixes the problem where you have to switch tabs. I've opened #91 to upgrade the client library we use which should fix the remaining issues where purchases aren't being applied properly.
