### ISSUE TITLE
GitHub button

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#95]
Add a GitHub button/link permanently to game front.

**Comment by codeka** [comment]
I prefer that it's slightly hidden, I don't want to get spammed by newbies with millions of random things. I think I refer to the bug list often enough that people will find it (or they can ask in game).

**Comment by Hexan1** [comment]
I guess the main reason I suggested this was the number of bugs n complaints on Forum. A lot of these are old and out-of-date. They also clutter up the search for help entries. The General tag is really over-broad and becomes a dumping ground. Currently I can only edit and delete my own entries. Some posts there have segued into relating to a help topic or other non-bug, non-complaint topic. This all could use some serious management to keep it fresh and current.


-------- Original message --------
