### ISSUE TITLE
Build research 2 not working

### ISSUE THREAD

**Issue by Hexan1** [codeka/wwmmo#96]
Cannot start a level 2 research lab.

**Comment by Mentaz** [comment]
Level 1 research lab Is "already at max level" so it cannot be upgraded.  Hence cannot build WH disrupter.  Lab was built before the recent Ww update that introduced disrupters.

![screenshot_2015-01-14-13-53-40](https://cloud.githubusercontent.com/assets/10536069/5745535/8ed63186-9bf7-11e4-8779-0f2559bf3d54.png)

**Comment by codeka** [comment]
Sorry, there was an error on the server that's been fixed now.
