### ISSUE TITLE
Purchase Button along with Build

### ISSUE THREAD

**Issue by coherentones** [codeka/wwmmo#99]
For buildings especially, but also for ships, it would save a lot of time and tedium to be able to purchase a building/upgrade instead of putting in the order and then having to go back to accelerate it.

**Comment by coherentones** [comment]
I'm thinking of the screen where you select the Build or Upgrade for buildings, to have the Purchase Button.

**Comment by codeka** [comment]
v2 won't have build speed-up as there won't be cash. Timing of all builds will be adjusted though.
